name: Deploy - NestJS (development)

on:
  push:
    branches: ['development']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy over SSH with PM2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/html/development-cicd/cf-nest-api-v2
            git fetch --all
            git reset --hard origin/development
            npm ci --omit=dev
            npm run build
            pm2 reload ecosystem.config.js --env development
