name: Deploy - NestJS (staging)

on:
  push:
    branches: ['staging']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy over SSH with PM2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/staging-cicd/cf-nest-api-v2
            git fetch --all
            git reset --hard origin/staging
            npm ci --omit=dev
            npm run build
            pm2 reload ecosystem.config.js --only stag-cf-nest-api-v2 || pm2 start ecosystem.config.js --only stag-cf-nest-api-v2
